- package.json
Due to conflicts with different versions of angular packages it would be better to have the library's dependencies declared as peerDependencies. This addresses that and only exposes the packages that are used by the library at runtime as peerDependencies.
Closes #57, #58
> Moves dependencies to peerDependencies

- src/components/split.component.ts
Proposing an equivalent implementation that works around an issue when this plugin is used in Adobe Panel applications (built on Chromium Embedded Platform).
The issue is that, for such applications running specifically on MacOS, `MouseEvent.screenY` returns coordinates that are inverted; up is down and down is up. This causes undesirable behavior when dragging gutters, as they move the opposite direction of the mouse drag.
`MouseEvent.pageY` provides equivalent information, and doesn't display this behavior in this (admittedly, special-case) situation.
> Switching to pageX/Y to resolve Y-coordinate inversion on mac for specific applications

- projects/angular-split/src/lib/module.ts
- src/app/examples/access-from-class/access-from-class.module.ts
- src/app/examples/collapse-expand/collapse-expand.module.ts
- src/app/examples/custom-gutter-style/custom-gutter-style.module.ts
- src/app/examples/dir-rtl/dir-rtl.module.ts
- src/app/examples/geek-demo/geek-demo.module.ts
- src/app/examples/gutter-click-roll-unroll/gutter-click-roll-unroll.module.ts
- src/app/examples/iframes/iframes.module.ts
- src/app/examples/min-max-split/min-max-split.module.ts
- src/app/examples/nested-split/nested-split.module.ts
- src/app/examples/simple/simple.module.ts
- src/app/examples/split-transitions/split-transitions.module.ts
- src/app/examples/sync-split/sync-split.module.ts
- src/app/examples/toggling-dom-and-visibility/toggling-dom-and-visibility.module.ts
- src/app/examples/workspace-localstorage/workspace-localstorage.module.ts
- src/app/home/home.component.ts
- src/app/ui/ui.module.ts
The `.forRoot()` and `.forChild()` methods did not add any additional options or configurations and are thus not needed.
In this PR the methods are deprecated and will show a warning, in the next major release they will be removed.
> feat: deprecate .forRoot() and .forChild() methods

- cypress/integration/7.click.spec.js
- projects/angular-split/src/lib/component/split.component.ts
Currently, angular-split doesn't always fire dragEnd event after dragStart instead it fires gutterClick / gutterDblClick when the cursor/touch position is not moved.
In this PR, dragStart is delayed until initial cursor/touch position move to avoid such inconsistency.
fixes #283
> fix: fire dragStart event only when a cursor is moved (#283)

- projects/angular-split/src/lib/component/split.component.ts
- projects/angular-split/src/lib/utils.ts
Currently, if using an overly sensitive mouse (a magic mouse on chrome on a mac as one example), the immediate clearing of `this._clickTimeout` in `dragEvent` results in double clicks (even with a long duration, e.g. 500ms) being cleared and thus not recognized. I didn't test to see if the same is true for a single click, but based on the existing code it looks like it might be true.
To fix this, we can do a standard practice of checking for deltas to account for drags before clearing the _clickTimeout or disregarding a click on a gutter. As this delta may need to be user configurable, I've suggested it also be an input parameter with a sensible default. Personally I think the default should not be 0px (which would reflect previous state) given that some of the angular-split functionality …
> Add a delta to mouse clicks and double clicks to avoid issues where double click does not get recognized

- src/app/documentation/documentation.component.ts
Fix #305: renamed classNames and components name
Changed `ui-` prefix to `as-` prefix
> Documentation issue: Fix old classNames and components prefix to new one

- cypress/integration/1.simple.spec.js
- cypress/integration/2.minmax.spec.js
- cypress/integration/3.nested.spec.js
- cypress/integration/4.sync.spec.js
- cypress/integration/5.style.spec.js
- cypress/integration/7.click.spec.js
- cypress/integration/9.geek.spec.js
- cypress/support/splitUtils.js
- projects/angular-split/src/lib/component/split.component.scss
- projects/angular-split/src/lib/component/split.component.ts
- projects/angular-split/src/lib/utils.ts
- src/app/examples/simple-split/simple-split.component.ts
Bringing back an old pull request from Michelle to add keyboard accessibility: https://github.com/angular-split/angular-split/pull/269.
From Michelle's PR:
- Added "startKeyboardDrag", which uses new util functions to calculate the start and end points differently from mouse events.
- Moved chunks of "startMouseDrag" out into separate functions so that keyboard drag can share the code: this.startDragging(), this.drag();, this.stopDragging();
- Consumers are able to optionally add a text for aria-label via @Input().
Additional features:
- Added role="slider" and made the dragger/gutter tab-able. 
- Added aria-orientation, aria-valuemin, aria-valuemax, aria-valuenow, aria-valuetext.
- Added PageUp and PageDown support. Arrow keys does a step offset of 50. PageUp and PageDown does a step …
> Add keyboard accessibility

- projects/angular-split/src/lib/component/split.component.scss
Adding a transparent 1x1 background image so that no spurious network call is shown. Particularly reproducible in electron env's.
> fix: spurious network call due to empty background image #316

- angular.json
- projects/angular-split/src/lib/component/split.component.ts
- projects/angular-split/src/lib/directive/split-area.directive.ts
- projects/angular-split/src/lib/interface.ts
- projects/angular-split/src/lib/utils.ts
- src/app/examples/custom-gutter-style/custom-gutter-style.component.ts
- src/app/examples/dir-rtl/dir-rtl.component.ts
- src/app/examples/geek-demo/geek-demo.component.ts
- src/app/examples/gutter-click-roll-unroll/gutter-click-roll-unroll.component.ts
- src/app/examples/simple-split/simple-split.component.ts
- src/app/examples/split-transitions/split-transitions.component.ts
- src/app/examples/workspace-localstorage/workspace-localstorage.component.ts
- tsconfig.json
Fix #220 
Features:
1. size is typed as `*` or `number`
2. `number` and `boolean` inputs support strings too (`prop="40"` and `prop="true"`)
3. New types: `ISplitDirection`, `ISplitDir`, `IAreaSize`, `ISplitUnit`
4. Fully compatible with strict templates considering all above too
> feat: support angular compiler strict templates

- package.json
- src/app/examples/workspace-localstorage/workspace-localstorage.component.ts
- yarn.lock
The demo app depended on `lodash` for `cloneDeep`, but we can use [structuredClone](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) which is supported in all major browsers.
It removes this warning:
> Warning: /Users/beeman/dev/github/angular-split/angular-split/src/app/examples/workspace-localstorage/workspace-localstorage.component.ts depends on 'lodash'. CommonJS or AMD dependencies can cause optimization bailouts.
> chore: remove lodash dependency

- angular.json
Updates `angular.json` so it's more in line with a new clean Angular app.
This also removes the following warning when running the dev server:
> Warning: 'outputHashing' option is disabled when using the dev-server.
> chore: update angular.json to modern standards

- projects/angular-split/src/lib/directive/split-area.directive.ts
Currently we don't support more than a single wildcard - but if no area size was provided or wrong area sizes the default logic in percent mode for example is splitting the size equally (kind of multiple wildcards).
This change make split areas without size work again even though this is invalid. The problem can be seen in the collapse example which has no tests coverage (another issue for another time).
We should think how to handle it - size required? Support multiple wildcards?
> fix: change default area size from null to *

- cypress/e2e/5.style.cy.js
- projects/angular-split/src/lib/component/split.component.ts
- projects/angular-split/src/lib/gutter/gutter-num-token.ts
- projects/angular-split/src/lib/gutter/split-gutter-drag-handle.directive.ts
- projects/angular-split/src/lib/gutter/split-gutter-dynamic-injector.directive.ts
- projects/angular-split/src/lib/gutter/split-gutter-exclude-from-drag.directive.ts
- projects/angular-split/src/lib/gutter/split-gutter.directive.ts
- projects/angular-split/src/lib/interface.ts
- projects/angular-split/src/lib/module.ts
- projects/angular-split/src/public_api.ts
- src/app/documentation/documentation.component.html
- src/app/documentation/documentation.component.ts
- src/app/examples/custom-gutter-style/custom-gutter-style.component.scss
- src/app/examples/custom-gutter-style/custom-gutter-style.component.ts
This adds support for custom gutter template customization.
There are three main features included:
1. A new structural directive to allow gutter template customization (`asSplitGutter`).
The usage as follows:
```html
<as-split>
<div *asSplitGutter>...</div>
<as-split-area>...</as-split-area>
...
</as-split>
```
The new `asSplitGutter` directive allows access to the following context:
```ts
export interface SplitGutterTemplateContext {
/**
* The area before the gutter.
* In RTL the right area and in LTR the left area
*/
areaBefore: IArea
/**
* The area after the gutter.
* In RTL the left area and in LTR the right area
*/
areaAfter: IArea
/**
* The absolute number of the gutter based on direction (RTL and LTR).
* First gutter is 1, second is 2, etc...
*/
gutterNum: number
/**
* Whether …
```
> feat: support custom gutter template

- projects/angular-split/src/lib/component/split.component.ts
Adds tabindex Input for split component & defaults to previous fixed value of 0.
Closes https://github.com/angular-split/angular-split/issues/432
> feat: add tabindex input and binding

- projects/angular-split/src/lib/split-area/split-area.component.ts
- projects/angular-split/src/lib/split/split.component.ts
When using jest for testing circular references are not allowed (while they are allowed for ng build and karma testing).
The origin of the circularity is `SplitComponent` referencing using `contentChildren` the `SplitAreaComponent` while `SplitAreaComponent` also injects `SplitComponent`.
To break the circular reference - an injection token is introduced to allow type only import of `SplitAreaComponent`.
Related to: https://github.com/angular-split/angular-split/issues/441#issuecomment-2311931230
> fix: break circular reference between split and split-area

- projects/angular-split/src/lib/utils.ts
As firefox doesn't have `TouchEvent` defined for non touch capable devices another check is required.
Based on https://github.com/angular-split/angular-split/issues/441#issuecomment-2270716240 
Fixes #454
> fix: handle TouchEvent in non touch capable devices for firefox

- cypress/e2e/10.toggle.cy.js
- cypress/support/splitUtils.js
- projects/angular-split/src/lib/split/split.component.ts
The visibility check happened before the slice operation which resulted in non visible areas before visible areas to get mixed up in the slice resulting in unresponsive gutters.
The correct approach is filtering after the slice and not before.
Fixes #449
> fix: filter non visible areas after indices array slice

- projects/angular-split/src/lib/split/split.component.ts
Grid columns transitions requires the same unit in order to work. This PR changes non wildcard hidden areas to 0px in pixel mode for transitions to work correctly.
There is still a transition bug when changing from `px` to `fr` or vice versa - but I don't have a good solution for it currently.
> fix: missing transition when hiding areas in pixel mode

- projects/angular-split/src/lib/split-area/split-area.component.ts
- projects/angular-split/src/lib/split/split.component.ts
- projects/angular-split/src/lib/utils.ts
- projects/angular-split/src/lib/validations.ts
Drop the validation effect that also updates internal sizes (with allow signal writes) and use computed instead as per the official angular recommendation.
The signal flow is now:
1. `SplitArea` has `visible` and `size`
2. `Split` creates `_visibleAreas` based on `SplitArea` `visible`
3. `Split` creates `_alignedVisibleAreasSizes` based on `_visibleAreas` and `SplitArea` `size` with validation alignments
4. `SplitArea` `_internalSize` is based on `_alignedVisibleAreasSizes`
5. `_internalSize` is the actual size anything else should use (except validations and normalizations)
> refactor: drop signal writes effect

- projects/angular-split/src/lib/split/split.component.ts
Chrome fires both `mousedown` and `touchstart` events. When split is disabled there was no prevent default which resulted in two click events firing. This means that clicking on a disabled gutter and changing size will not work (see https://angular-split.github.io/examples/gutter-click-roll-unroll in mobile mode using chrome devtools and clicking the gutter)
> fix: disabled split gutter interactions

- projects/angular-split/src/lib/split/split.component.ts
- src/app/examples/split-transitions/split-transitions.component.ts
@Harpush  @Jefiozie 
I moved the effect to afterrendereffect, and moved the other effect into 'host' 
With this change, we no longer need to use `renderer2` in the component.  Also, AFAIK, there is no change in the CD of the parent component.  Using the computed value ensures that the thing is debounced as accurately as possible.
I'm not 100% sure about this thing tho, so please review carefully
should closes #513
> fix: use afterRender and host
