- README.md
This is one way to structure it a little cleaner. Let me know if you like it. If not I can try something different.
> Update wording for README

- projects/angular-split/src/lib/component/split.component.ts
> wait for drag-end postprocessing before starting next drag

- projects/angular-split/src/lib/component/split.component.scss
> Hidden panes fix for IE11

- src_app/app/component/doc/doc.route.component.ts
Properties are sorted alphabetically
Document order property, fixes #234
> chore: update documentation

- CHANGELOG.md
- projects/angular-split/package.json
- src_app/app/component/examples/classAccess.route.component.ts
> fix: undefined errors in access-from-class demo

- package-lock.json
- projects/angular-split/src/lib/component/split.component.scss
- projects/angular-split/src/lib/component/split.component.ts
- projects/angular-split/src/lib/directive/splitArea.directive.ts
- projects/angular-split/src/lib/interface.ts
- src_app/app/app.module.ts
- src_app/app/component/examples/collapseExpandArea.route.component.ts
- src_app/app/data/enum.ts
- src_app/app/data/listExamples.ts
> NEW expand collapse code & examples

- CHANGELOG.md
- projects/angular-split/package.json
- projects/angular-split/src/public_api.ts
> Export interfaces

- package.json
- projects/angular-split/src/lib/component/split.component.ts
- src/app/examples/dir-rtl/dir-rtl.component.ts
> fix: handle rtl in vertical direction correctly

- projects/angular-split/src/lib/component/split.component.ts
> fix: role should be separator and not slider

- cypress/e2e/1.simple.cy.js
- projects/angular-split/src/lib/component/split.component.ts
- projects/angular-split/src/lib/utils.ts
- src/app/examples/simple-split/simple-split.component.ts
> feat: add wildcard support for percent mode

- projects/angular-split/src/lib/module.ts
> fix: remove deprecated forRoot and forChild

- .all-contributorsrc
- README.md
This will introduce the all contribors bot to recognize contributions
Closes #371
> feat: introduce all contributors to the repo closes #371

- CODE_OF_CONDUCT.md
Implemented code of conduct
Fixes #372
> docs: create code of conduct fixes

- package-lock.json
related to issue #435
This package-lock should work on windows. Awaiting result form that.
> test: fixed package-lock

- projects/angular-split/src/lib/component/split.component.ts
Reverts angular-split/angular-split#438
> Revert: "feat: add tabindex input and binding"

- projects/angular-split/package.json
> chore: release 18.0.0

- .github/workflows/tests.yml
- package.json
> feat: support node v22

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/tests.yml
- package-lock.json
- package.json
> ci: use npm instead of yarn

- projects/angular-split/package.json
* fix: update to release-it and update changelog
* ci: remove some parts and updated settings
* refactor: improve release cycle and copy changelog
* build: remove not needed file
* refactor: latest fixes
> fix: update to release-it and update changelog (#484)

- projects/angular-split/src/lib/split-area/split-area.component.ts
- projects/angular-split/src/lib/utils.ts
The mirror signal was a polyfill until v19 linkedSignal
> feat: drop mirror signal in favor of linked signal

- src/app/examples/dir-rtl/dir-rtl.component.ts
- src/app/examples/split-transitions/split-transitions.component.ts
- src/app/examples/workspace-localstorage/workspace-localstorage.component.ts
Due to wrong imports some example pages are not working
> fix: crashing example pages

- CONTRIBUTING.md
- README.md
> docs: update readme and add setup instructions to contirbutors.md
